### ISSUE TITLE
Including this with Meteor.js

### ISSUE THREAD

**Issue by macsj200** [EasyPost/easypost-node#85]
Something's wrong with my babel configuration inside of Meteor 1.4.4.2. When I try to use this npm module, my console spits out

```
W20170716-11:30:05.474(-7)? (STDERR) /Users/maxjohansen/.meteor/packages/meteor-tool/.1.4.4_2.ja69s4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170716-11:30:05.475(-7)? (STDERR) 						throw(ex);
W20170716-11:30:05.475(-7)? (STDERR) 						^
W20170716-11:30:05.475(-7)? (STDERR) 
W20170716-11:30:05.475(-7)? (STDERR) ReferenceError: regeneratorRuntime is not defined
W20170716-11:30:05.475(-7)? (STDERR)     at /Users/maxjohansen/projects/hackfactory/Koena/node_modules/@easypost/api/easypost.js:1:49866
W20170716-11:30:05.475(-7)? (STDERR)     at /Users/maxjohansen/projects/hackfactory/Koena/node_modules/@easypost/api/easypost.js:1:50702
W20170716-11:30:05.475(-7)? (STDERR)     at Object.create.constructor.value (/Users/maxjohansen/projects/hackfactory/Koena/node_modules/@easypost/api/easypost.js:1:51051)
W20170716-11:30:05.476(-7)? (STDERR)     at t (/Users/maxjohansen/projects/hackfactory/Koena/node_modules/@easypost/api/easypost.js:1:149)
W20170716-11:30:05.476(-7)? (STDERR)     at e.__esModule.default (/Users/maxjohansen/projects/hackfactory/Koena/node_modules/@easypost/api/easypost.js:1:532)
W20170716-11:30:05.476(-7)? (STDERR)     at Object.<anonymous> (/Users/maxjohansen/projects/hackfactory/Koena/node_modules/@easypost/api/easypost.js:1:542)
W20170716-11:30:05.477(-7)? (STDERR)     at Module._compile (module.js:409:26)
W20170716-11:30:05.477(-7)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
W20170716-11:30:05.478(-7)? (STDERR)     at Module.load (module.js:343:32)
W20170716-11:30:05.478(-7)? (STDERR)     at Function.Module._load (module.js:300:12)
```

**Comment by k-funk** [comment]
Please provide a code sample that also includes your import.

**Comment by ajacksified** [comment]
@macsj200, since you're using an older version of node, require the `regenerator-runtime` (https://www.npmjs.com/package/regenerator-runtime) package in your application before `require('@easypost/api')`.
