### ISSUE TITLE
Cannot find module 'nodent-runtime'

### ISSUE THREAD

**Issue by AugustBrenner** [EasyPost/easypost-node#89]
Error: Cannot find module 'nodent-runtime'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/{...}/node_modules/@easypost/api/easypost.js:83:18)

I think you might need to add nodent-runtime to the package.json

**Comment by ajacksified** [comment]
Will deploy as 3.1.1.
