### ISSUE TITLE
Issue calling API

### ISSUE THREAD

**Issue by SBero** [EasyPost/easypost-node#93]
The included library works fine when I'm using our api test key, but using the production key, and we get the following error:

You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
[object Object]
    at a.<anonymous> (/var/node/node_modules/@easypost/api/easypost.js:160:5099)
    at Generator.throw (<anonymous>)
    at d (/var/node/node_modules/@easypost/api/easypost.js:160:2584)
    at /var/node/node_modules/@easypost/api/easypost.js:160:2709
    at run (/var/node/node_modules/core-js/modules/es6.promise.js:66:22)
    at /var/node/node_modules/core-js/modules/es6.promise.js:79:30
    at flush (/var/node/node_modules/core-js/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

Any thoughts?

node v8.5.0
pm2 v2.7.0

module v3.2.1

**Comment by SBero** [comment]
Once we wrapped the generator methods in a try-catch block we were able to properly handle the error to realize we needed to fund our account for production use! :-|
